//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pecuniaus.Resources.Renewal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Renewal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Renewal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pecuniaus.Resources.Renewal.Renewal", typeof(Renewal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Turn.
        /// </summary>
        public static string actualturn {
            get {
                return ResourceManager.GetString("actualturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string btnComplete {
            get {
                return ResourceManager.GetString("btnComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string btnDecline {
            get {
                return ResourceManager.GetString("btnDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string btnDetail {
            get {
                return ResourceManager.GetString("btnDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze.
        /// </summary>
        public static string btnSnooze {
            get {
                return ResourceManager.GetString("btnSnooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        public static string businessName {
            get {
                return ResourceManager.GetString("businessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContractId.
        /// </summary>
        public static string contractId {
            get {
                return ResourceManager.GetString("contractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Status.
        /// </summary>
        public static string contractStatus {
            get {
                return ResourceManager.GetString("contractStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Scanning.
        /// </summary>
        public static string DocumentScanning {
            get {
                return ResourceManager.GetString("DocumentScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type is required.
        /// </summary>
        public static string DocumentTypeRequired {
            get {
                return ResourceManager.GetString("DocumentTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Verification.
        /// </summary>
        public static string DocVerification {
            get {
                return ResourceManager.GetString("DocVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string dollar {
            get {
                return ResourceManager.GetString("dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ever in Collection.
        /// </summary>
        public static string everInCollection {
            get {
                return ResourceManager.GetString("everInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Date.
        /// </summary>
        public static string expectedDate {
            get {
                return ResourceManager.GetString("expectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Turn.
        /// </summary>
        public static string expectedturn {
            get {
                return ResourceManager.GetString("expectedturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funded Date.
        /// </summary>
        public static string fundedDate {
            get {
                return ResourceManager.GetString("fundedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCA Amount.
        /// </summary>
        public static string loanamount {
            get {
                return ResourceManager.GetString("loanamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Merchants.
        /// </summary>
        public static string merchantList {
            get {
                return ResourceManager.GetString("merchantList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Name.
        /// </summary>
        public static string merchantName {
            get {
                return ResourceManager.GetString("merchantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Status.
        /// </summary>
        public static string merchantStatus {
            get {
                return ResourceManager.GetString("merchantStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Creation.
        /// </summary>
        public static string OfferList {
            get {
                return ResourceManager.GetString("OfferList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owed Amount.
        /// </summary>
        public static string ownedAmount {
            get {
                return ResourceManager.GetString("ownedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        public static string paidamount {
            get {
                return ResourceManager.GetString("paidamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid % age.
        /// </summary>
        public static string paidpercent {
            get {
                return ResourceManager.GetString("paidpercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze till paid off % age.
        /// </summary>
        public static string paidpercentage {
            get {
                return ResourceManager.GetString("paidpercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Amount.
        /// </summary>
        public static string pendingAmount {
            get {
                return ResourceManager.GetString("pendingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of merchants qualifying for renewals.
        /// </summary>
        public static string qualifyMerchant {
            get {
                return ResourceManager.GetString("qualifyMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Turn:.
        /// </summary>
        public static string rActualTurn {
            get {
                return ResourceManager.GetString("rActualTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Evaluation.
        /// </summary>
        public static string RenewalEvaluation {
            get {
                return ResourceManager.GetString("RenewalEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Review.
        /// </summary>
        public static string RenewalReview {
            get {
                return ResourceManager.GetString("RenewalReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Workflow.
        /// </summary>
        public static string renewalWorkflow {
            get {
                return ResourceManager.GetString("renewalWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ever In Collection:.
        /// </summary>
        public static string rEverInCollection {
            get {
                return ResourceManager.GetString("rEverInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Task.
        /// </summary>
        public static string ReviewTask {
            get {
                return ResourceManager.GetString("ReviewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Tern:.
        /// </summary>
        public static string rExpectedTurn {
            get {
                return ResourceManager.GetString("rExpectedTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funded Date:.
        /// </summary>
        public static string rFundedDate {
            get {
                return ResourceManager.GetString("rFundedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaned Amount:.
        /// </summary>
        public static string rLoanedAmount {
            get {
                return ResourceManager.GetString("rLoanedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant ID:.
        /// </summary>
        public static string rMerchantId {
            get {
                return ResourceManager.GetString("rMerchantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Name:.
        /// </summary>
        public static string rMerchantName {
            get {
                return ResourceManager.GetString("rMerchantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Status:.
        /// </summary>
        public static string rMerchantStatus {
            get {
                return ResourceManager.GetString("rMerchantStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owend Amount:.
        /// </summary>
        public static string rOwendAmount {
            get {
                return ResourceManager.GetString("rOwendAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount:.
        /// </summary>
        public static string rPaidAmountt {
            get {
                return ResourceManager.GetString("rPaidAmountt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid % Age:.
        /// </summary>
        public static string rPaidPercentage {
            get {
                return ResourceManager.GetString("rPaidPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name:.
        /// </summary>
        public static string rTaskName {
            get {
                return ResourceManager.GetString("rTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Status:.
        /// </summary>
        public static string rTaskStatus {
            get {
                return ResourceManager.GetString("rTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze till date.
        /// </summary>
        public static string snoozeDate {
            get {
                return ResourceManager.GetString("snoozeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze till paid off % age:.
        /// </summary>
        public static string snoozePaidercent {
            get {
                return ResourceManager.GetString("snoozePaidercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        public static string taskName {
            get {
                return ResourceManager.GetString("taskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Status.
        /// </summary>
        public static string taskstatus {
            get {
                return ResourceManager.GetString("taskstatus", resourceCulture);
            }
        }
    }
}
