//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pecuniaus.Resources.Contract {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CorpDocVerification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CorpDocVerification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pecuniaus.Resources.Contract.CorpDocVerification", typeof(CorpDocVerification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Document Verification.
        /// </summary>
        public static string CorporateDocumentVerification {
            get {
                return ResourceManager.GetString("CorporateDocumentVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Authorized.
        /// </summary>
        public static string IsAuthorized {
            get {
                return ResourceManager.GetString("IsAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Authorized is required..
        /// </summary>
        public static string IsAuthorizedReq {
            get {
                return ResourceManager.GetString("IsAuthorizedReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Company.
        /// </summary>
        public static string NameOfCompany {
            get {
                return ResourceManager.GetString("NameOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Of Company is required..
        /// </summary>
        public static string NameOfCompanyReq {
            get {
                return ResourceManager.GetString("NameOfCompanyReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Last Name.
        /// </summary>
        public static string OwnerLastName {
            get {
                return ResourceManager.GetString("OwnerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Last Name is required..
        /// </summary>
        public static string OwnerLastNameReq {
            get {
                return ResourceManager.GetString("OwnerLastNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner First Name.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner First Name is required..
        /// </summary>
        public static string OwnerNameReq {
            get {
                return ResourceManager.GetString("OwnerNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number / ID.
        /// </summary>
        public static string PassportNbr {
            get {
                return ResourceManager.GetString("PassportNbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number ID is required..
        /// </summary>
        public static string PassportNbrReq {
            get {
                return ResourceManager.GetString("PassportNbrReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNC.
        /// </summary>
        public static string RNCNumber {
            get {
                return ResourceManager.GetString("RNCNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNC is required..
        /// </summary>
        public static string RNCNumberReq {
            get {
                return ResourceManager.GetString("RNCNumberReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number is required..
        /// </summary>
        public static string TelephoneReq {
            get {
                return ResourceManager.GetString("TelephoneReq", resourceCulture);
            }
        }
    }
}
