//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pecuniaus.Resources.Contract {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataEntry {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataEntry() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pecuniaus.Resources.Contract.DataEntry", typeof(DataEntry).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        public static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1 is required..
        /// </summary>
        public static string AddressLine1Req {
            get {
                return ResourceManager.GetString("AddressLine1Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        public static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate Number.
        /// </summary>
        public static string AffiliateNumber {
            get {
                return ResourceManager.GetString("AffiliateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate Number is required..
        /// </summary>
        public static string AffiliateNumberReq {
            get {
                return ResourceManager.GetString("AffiliateNumberReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Sales.
        /// </summary>
        public static string AnnualSales {
            get {
                return ResourceManager.GetString("AnnualSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Annual Sales Calculation File.
        /// </summary>
        public static string AnnualSalesCalcReq {
            get {
                return ResourceManager.GetString("AnnualSalesCalcReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Sales Calculation File.
        /// </summary>
        public static string AnnualSalesFile {
            get {
                return ResourceManager.GetString("AnnualSalesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Sales is required..
        /// </summary>
        public static string AnnualSalesReq {
            get {
                return ResourceManager.GetString("AnnualSalesReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized.
        /// </summary>
        public static string Authorized {
            get {
                return ResourceManager.GetString("Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized is required..
        /// </summary>
        public static string AuthorizedReq {
            get {
                return ResourceManager.GetString("AuthorizedReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Name.
        /// </summary>
        public static string BankAccountName {
            get {
                return ResourceManager.GetString("BankAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Number.
        /// </summary>
        public static string BankAccountNumber {
            get {
                return ResourceManager.GetString("BankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        public static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name is Required.
        /// </summary>
        public static string BusinessNameReq {
            get {
                return ResourceManager.GetString("BusinessNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Start Date.
        /// </summary>
        public static string BusinessStartDate {
            get {
                return ResourceManager.GetString("BusinessStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Start Date is required..
        /// </summary>
        public static string BusinessStartDateReq {
            get {
                return ResourceManager.GetString("BusinessStartDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Number.
        /// </summary>
        public static string CellNumber {
            get {
                return ResourceManager.GetString("CellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Number is required..
        /// </summary>
        public static string CellNumberReq {
            get {
                return ResourceManager.GetString("CellNumberReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Number must be Ten digit long..
        /// </summary>
        public static string CellNumberVal {
            get {
                return ResourceManager.GetString("CellNumberVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities is required..
        /// </summary>
        public static string CitiesReq {
            get {
                return ResourceManager.GetString("CitiesReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required..
        /// </summary>
        public static string CityReq {
            get {
                return ResourceManager.GetString("CityReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Vaild Email Address..
        /// </summary>
        public static string EmailValidReq {
            get {
                return ResourceManager.GetString("EmailValidReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Processed Date.
        /// </summary>
        public static string FirstProcessedDate {
            get {
                return ResourceManager.GetString("FirstProcessedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Processed Date is required..
        /// </summary>
        public static string FirstProcessedDateReq {
            get {
                return ResourceManager.GetString("FirstProcessedDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Yearly Sale.
        /// </summary>
        public static string GrossYearlySale {
            get {
                return ResourceManager.GetString("GrossYearlySale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Yearly Sale is required..
        /// </summary>
        public static string GrossYearlySaleReq {
            get {
                return ResourceManager.GetString("GrossYearlySaleReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Types.
        /// </summary>
        public static string IndustryTypes {
            get {
                return ResourceManager.GetString("IndustryTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Types is required..
        /// </summary>
        public static string IndustryTypesReq {
            get {
                return ResourceManager.GetString("IndustryTypesReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord Company Name.
        /// </summary>
        public static string LandlordCompanyName {
            get {
                return ResourceManager.GetString("LandlordCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord Company Name is required..
        /// </summary>
        public static string LandlordCompanyNameReq {
            get {
                return ResourceManager.GetString("LandlordCompanyNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord First Name.
        /// </summary>
        public static string LandlordFirstName {
            get {
                return ResourceManager.GetString("LandlordFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord First Name is required..
        /// </summary>
        public static string LandlordFirstNameReq {
            get {
                return ResourceManager.GetString("LandlordFirstNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord Last Name.
        /// </summary>
        public static string LandlordLastName {
            get {
                return ResourceManager.GetString("LandlordLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord Last Name is required..
        /// </summary>
        public static string LandlordLastNameReq {
            get {
                return ResourceManager.GetString("LandlordLastNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord Phone Number.
        /// </summary>
        public static string LandlordPhoneNumber {
            get {
                return ResourceManager.GetString("LandlordPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord Phone Number is required..
        /// </summary>
        public static string LandlordPhoneNumberReq {
            get {
                return ResourceManager.GetString("LandlordPhoneNumberReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Name.
        /// </summary>
        public static string LegalName {
            get {
                return ResourceManager.GetString("LegalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Name is required..
        /// </summary>
        public static string LegalNameReq {
            get {
                return ResourceManager.GetString("LegalNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCA Amount is required..
        /// </summary>
        public static string LoanAmountReq {
            get {
                return ResourceManager.GetString("LoanAmountReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCAAmount Required.
        /// </summary>
        public static string LoanAmountRequired {
            get {
                return ResourceManager.GetString("LoanAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant.
        /// </summary>
        public static string Merchant {
            get {
                return ResourceManager.GetString("Merchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Reference.
        /// </summary>
        public static string NameOfTheReference {
            get {
                return ResourceManager.GetString("NameOfTheReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Telephone Number.
        /// </summary>
        public static string OtherTelephoneNumber {
            get {
                return ResourceManager.GetString("OtherTelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Telephone Number is invalid..
        /// </summary>
        public static string OtherTelephoneVal {
            get {
                return ResourceManager.GetString("OtherTelephoneVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner1 {
            get {
                return ResourceManager.GetString("Owner1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string OwnerDOB {
            get {
                return ResourceManager.GetString("OwnerDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner DOB is required..
        /// </summary>
        public static string OwnerDOBReq {
            get {
                return ResourceManager.GetString("OwnerDOBReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string OwnerFirstName {
            get {
                return ResourceManager.GetString("OwnerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is required..
        /// </summary>
        public static string OwnerFirstNameRequired {
            get {
                return ResourceManager.GetString("OwnerFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string OwnerLastName {
            get {
                return ResourceManager.GetString("OwnerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is required..
        /// </summary>
        public static string OwnerLastNameRequired {
            get {
                return ResourceManager.GetString("OwnerLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid email..
        /// </summary>
        public static string OwnerValidEmail {
            get {
                return ResourceManager.GetString("OwnerValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID / Passport Number.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number is required..
        /// </summary>
        public static string PassportNumberReq {
            get {
                return ResourceManager.GetString("PassportNumberReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is required..
        /// </summary>
        public static string PhoneNumberReq {
            get {
                return ResourceManager.GetString("PhoneNumberReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number must be Ten digit long..
        /// </summary>
        public static string PhoneNumberVal {
            get {
                return ResourceManager.GetString("PhoneNumberVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        public static string Processor {
            get {
                return ResourceManager.GetString("Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Compar.
        /// </summary>
        public static string ProcessorCompar {
            get {
                return ResourceManager.GetString("ProcessorCompar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Compar is required..
        /// </summary>
        public static string ProcessorComparReq {
            get {
                return ResourceManager.GetString("ProcessorComparReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Number.
        /// </summary>
        public static string ProcessorNumber {
            get {
                return ResourceManager.GetString("ProcessorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Types.
        /// </summary>
        public static string PropertyTypes {
            get {
                return ResourceManager.GetString("PropertyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Types is required..
        /// </summary>
        public static string PropertyTypesReq {
            get {
                return ResourceManager.GetString("PropertyTypesReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provinces.
        /// </summary>
        public static string Provinces {
            get {
                return ResourceManager.GetString("Provinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Provinces is required..
        /// </summary>
        public static string ProvincesReq {
            get {
                return ResourceManager.GetString("ProvincesReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Amount.
        /// </summary>
        public static string RentAmount {
            get {
                return ResourceManager.GetString("RentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Amount is required..
        /// </summary>
        public static string RentAmountReq {
            get {
                return ResourceManager.GetString("RentAmountReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNC.
        /// </summary>
        public static string RNC {
            get {
                return ResourceManager.GetString("RNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNC is required..
        /// </summary>
        public static string RNCReq {
            get {
                return ResourceManager.GetString("RNCReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNC Number must 9 to 11 digit long..
        /// </summary>
        public static string RNCValidation {
            get {
                return ResourceManager.GetString("RNCValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Statement.
        /// </summary>
        public static string Statement {
            get {
                return ResourceManager.GetString("Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Month.
        /// </summary>
        public static string StatementMonth {
            get {
                return ResourceManager.GetString("StatementMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Year.
        /// </summary>
        public static string StatementYear {
            get {
                return ResourceManager.GetString("StatementYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States.
        /// </summary>
        public static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States is required..
        /// </summary>
        public static string StatesReq {
            get {
                return ResourceManager.GetString("StatesReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        public static string TelephoneNumber {
            get {
                return ResourceManager.GetString("TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number is invalid..
        /// </summary>
        public static string TelephoneVal {
            get {
                return ResourceManager.GetString("TelephoneVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Reference.
        /// </summary>
        public static string TradeRef {
            get {
                return ResourceManager.GetString("TradeRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Advances.
        /// </summary>
        public static string TypeOfAdvance {
            get {
                return ResourceManager.GetString("TypeOfAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Advances Required.
        /// </summary>
        public static string TypeOfAdvanceErr {
            get {
                return ResourceManager.GetString("TypeOfAdvanceErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Business entity.
        /// </summary>
        public static string TypeOfBusinessEntity {
            get {
                return ResourceManager.GetString("TypeOfBusinessEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code is required..
        /// </summary>
        public static string ZipCodeReq {
            get {
                return ResourceManager.GetString("ZipCodeReq", resourceCulture);
            }
        }
    }
}
