//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pecuniaus.Resources.Contract {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VerificationCall {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VerificationCall() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pecuniaus.Resources.Contract.VerificationCall", typeof(VerificationCall).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify Annual Sales.
        /// </summary>
        public static string AnnualSales {
            get {
                return ResourceManager.GetString("AnnualSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What City you born in.
        /// </summary>
        public static string BornCity {
            get {
                return ResourceManager.GetString("BornCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify your Business name.
        /// </summary>
        public static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is color of your First Car.
        /// </summary>
        public static string ColorOfFirstCar {
            get {
                return ResourceManager.GetString("ColorOfFirstCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify you Legal name.
        /// </summary>
        public static string LegalName {
            get {
                return ResourceManager.GetString("LegalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script File.
        /// </summary>
        public static string ScriptFile {
            get {
                return ResourceManager.GetString("ScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify Social Security Number.
        /// </summary>
        public static string SocialSecurityNumber {
            get {
                return ResourceManager.GetString("SocialSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Verification call.
        /// </summary>
        public static string UploadCallFileName {
            get {
                return ResourceManager.GetString("UploadCallFileName", resourceCulture);
            }
        }
    }
}
