//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bridge.AcmeRuby {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.datacredito1.com/CaltecService", ConfigurationName="AcmeRuby.clsCaltecServiceSoap")]
    public interface clsCaltecServiceSoap {
        
        // CODEGEN: Generating message contract since element name Username from namespace http://www.datacredito1.com/CaltecService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.datacredito1.com/CaltecService/GetXml", ReplyAction="*")]
        Bridge.AcmeRuby.GetXmlResponse GetXml(Bridge.AcmeRuby.GetXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.datacredito1.com/CaltecService/GetXml", ReplyAction="*")]
        System.Threading.Tasks.Task<Bridge.AcmeRuby.GetXmlResponse> GetXmlAsync(Bridge.AcmeRuby.GetXmlRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://www.datacredito1.com/CaltecService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.datacredito1.com/CaltecService/GetXmlJson", ReplyAction="*")]
        Bridge.AcmeRuby.GetXmlJsonResponse GetXmlJson(Bridge.AcmeRuby.GetXmlJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.datacredito1.com/CaltecService/GetXmlJson", ReplyAction="*")]
        System.Threading.Tasks.Task<Bridge.AcmeRuby.GetXmlJsonResponse> GetXmlJsonAsync(Bridge.AcmeRuby.GetXmlJsonRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://www.datacredito1.com/CaltecService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.datacredito1.com/CaltecService/GetXmlJsonStr", ReplyAction="*")]
        Bridge.AcmeRuby.GetXmlJsonStrResponse GetXmlJsonStr(Bridge.AcmeRuby.GetXmlJsonStrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.datacredito1.com/CaltecService/GetXmlJsonStr", ReplyAction="*")]
        System.Threading.Tasks.Task<Bridge.AcmeRuby.GetXmlJsonStrResponse> GetXmlJsonStrAsync(Bridge.AcmeRuby.GetXmlJsonStrRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXml", Namespace="http://www.datacredito1.com/CaltecService", Order=0)]
        public Bridge.AcmeRuby.GetXmlRequestBody Body;
        
        public GetXmlRequest() {
        }
        
        public GetXmlRequest(Bridge.AcmeRuby.GetXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.datacredito1.com/CaltecService")]
    public partial class GetXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TipoId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string xmlParameters;
        
        public GetXmlRequestBody() {
        }
        
        public GetXmlRequestBody(string Username, string Password, string TipoId, string Id, string xmlParameters) {
            this.Username = Username;
            this.Password = Password;
            this.TipoId = TipoId;
            this.Id = Id;
            this.xmlParameters = xmlParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlResponse", Namespace="http://www.datacredito1.com/CaltecService", Order=0)]
        public Bridge.AcmeRuby.GetXmlResponseBody Body;
        
        public GetXmlResponse() {
        }
        
        public GetXmlResponse(Bridge.AcmeRuby.GetXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.datacredito1.com/CaltecService")]
    public partial class GetXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetXmlResult;
        
        public GetXmlResponseBody() {
        }
        
        public GetXmlResponseBody(string GetXmlResult) {
            this.GetXmlResult = GetXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlJson", Namespace="http://www.datacredito1.com/CaltecService", Order=0)]
        public Bridge.AcmeRuby.GetXmlJsonRequestBody Body;
        
        public GetXmlJsonRequest() {
        }
        
        public GetXmlJsonRequest(Bridge.AcmeRuby.GetXmlJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.datacredito1.com/CaltecService")]
    public partial class GetXmlJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TipoId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string xmlParameters;
        
        public GetXmlJsonRequestBody() {
        }
        
        public GetXmlJsonRequestBody(string Username, string Password, string TipoId, string Id, string xmlParameters) {
            this.Username = Username;
            this.Password = Password;
            this.TipoId = TipoId;
            this.Id = Id;
            this.xmlParameters = xmlParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlJsonResponse", Namespace="http://www.datacredito1.com/CaltecService", Order=0)]
        public Bridge.AcmeRuby.GetXmlJsonResponseBody Body;
        
        public GetXmlJsonResponse() {
        }
        
        public GetXmlJsonResponse(Bridge.AcmeRuby.GetXmlJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetXmlJsonResponseBody {
        
        public GetXmlJsonResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlJsonStrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlJsonStr", Namespace="http://www.datacredito1.com/CaltecService", Order=0)]
        public Bridge.AcmeRuby.GetXmlJsonStrRequestBody Body;
        
        public GetXmlJsonStrRequest() {
        }
        
        public GetXmlJsonStrRequest(Bridge.AcmeRuby.GetXmlJsonStrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.datacredito1.com/CaltecService")]
    public partial class GetXmlJsonStrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TipoId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string xmlParameters;
        
        public GetXmlJsonStrRequestBody() {
        }
        
        public GetXmlJsonStrRequestBody(string Username, string Password, string TipoId, string Id, string xmlParameters) {
            this.Username = Username;
            this.Password = Password;
            this.TipoId = TipoId;
            this.Id = Id;
            this.xmlParameters = xmlParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlJsonStrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlJsonStrResponse", Namespace="http://www.datacredito1.com/CaltecService", Order=0)]
        public Bridge.AcmeRuby.GetXmlJsonStrResponseBody Body;
        
        public GetXmlJsonStrResponse() {
        }
        
        public GetXmlJsonStrResponse(Bridge.AcmeRuby.GetXmlJsonStrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.datacredito1.com/CaltecService")]
    public partial class GetXmlJsonStrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetXmlJsonStrResult;
        
        public GetXmlJsonStrResponseBody() {
        }
        
        public GetXmlJsonStrResponseBody(string GetXmlJsonStrResult) {
            this.GetXmlJsonStrResult = GetXmlJsonStrResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface clsCaltecServiceSoapChannel : Bridge.AcmeRuby.clsCaltecServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class clsCaltecServiceSoapClient : System.ServiceModel.ClientBase<Bridge.AcmeRuby.clsCaltecServiceSoap>, Bridge.AcmeRuby.clsCaltecServiceSoap {
        
        public clsCaltecServiceSoapClient() {
        }
        
        public clsCaltecServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public clsCaltecServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public clsCaltecServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public clsCaltecServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bridge.AcmeRuby.GetXmlResponse Bridge.AcmeRuby.clsCaltecServiceSoap.GetXml(Bridge.AcmeRuby.GetXmlRequest request) {
            return base.Channel.GetXml(request);
        }
        
        public string GetXml(string Username, string Password, string TipoId, string Id, string xmlParameters) {
            Bridge.AcmeRuby.GetXmlRequest inValue = new Bridge.AcmeRuby.GetXmlRequest();
            inValue.Body = new Bridge.AcmeRuby.GetXmlRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.TipoId = TipoId;
            inValue.Body.Id = Id;
            inValue.Body.xmlParameters = xmlParameters;
            Bridge.AcmeRuby.GetXmlResponse retVal = ((Bridge.AcmeRuby.clsCaltecServiceSoap)(this)).GetXml(inValue);
            return retVal.Body.GetXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bridge.AcmeRuby.GetXmlResponse> Bridge.AcmeRuby.clsCaltecServiceSoap.GetXmlAsync(Bridge.AcmeRuby.GetXmlRequest request) {
            return base.Channel.GetXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bridge.AcmeRuby.GetXmlResponse> GetXmlAsync(string Username, string Password, string TipoId, string Id, string xmlParameters) {
            Bridge.AcmeRuby.GetXmlRequest inValue = new Bridge.AcmeRuby.GetXmlRequest();
            inValue.Body = new Bridge.AcmeRuby.GetXmlRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.TipoId = TipoId;
            inValue.Body.Id = Id;
            inValue.Body.xmlParameters = xmlParameters;
            return ((Bridge.AcmeRuby.clsCaltecServiceSoap)(this)).GetXmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bridge.AcmeRuby.GetXmlJsonResponse Bridge.AcmeRuby.clsCaltecServiceSoap.GetXmlJson(Bridge.AcmeRuby.GetXmlJsonRequest request) {
            return base.Channel.GetXmlJson(request);
        }
        
        public void GetXmlJson(string Username, string Password, string TipoId, string Id, string xmlParameters) {
            Bridge.AcmeRuby.GetXmlJsonRequest inValue = new Bridge.AcmeRuby.GetXmlJsonRequest();
            inValue.Body = new Bridge.AcmeRuby.GetXmlJsonRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.TipoId = TipoId;
            inValue.Body.Id = Id;
            inValue.Body.xmlParameters = xmlParameters;
            Bridge.AcmeRuby.GetXmlJsonResponse retVal = ((Bridge.AcmeRuby.clsCaltecServiceSoap)(this)).GetXmlJson(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bridge.AcmeRuby.GetXmlJsonResponse> Bridge.AcmeRuby.clsCaltecServiceSoap.GetXmlJsonAsync(Bridge.AcmeRuby.GetXmlJsonRequest request) {
            return base.Channel.GetXmlJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bridge.AcmeRuby.GetXmlJsonResponse> GetXmlJsonAsync(string Username, string Password, string TipoId, string Id, string xmlParameters) {
            Bridge.AcmeRuby.GetXmlJsonRequest inValue = new Bridge.AcmeRuby.GetXmlJsonRequest();
            inValue.Body = new Bridge.AcmeRuby.GetXmlJsonRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.TipoId = TipoId;
            inValue.Body.Id = Id;
            inValue.Body.xmlParameters = xmlParameters;
            return ((Bridge.AcmeRuby.clsCaltecServiceSoap)(this)).GetXmlJsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bridge.AcmeRuby.GetXmlJsonStrResponse Bridge.AcmeRuby.clsCaltecServiceSoap.GetXmlJsonStr(Bridge.AcmeRuby.GetXmlJsonStrRequest request) {
            return base.Channel.GetXmlJsonStr(request);
        }
        
        public string GetXmlJsonStr(string Username, string Password, string TipoId, string Id, string xmlParameters) {
            Bridge.AcmeRuby.GetXmlJsonStrRequest inValue = new Bridge.AcmeRuby.GetXmlJsonStrRequest();
            inValue.Body = new Bridge.AcmeRuby.GetXmlJsonStrRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.TipoId = TipoId;
            inValue.Body.Id = Id;
            inValue.Body.xmlParameters = xmlParameters;
            Bridge.AcmeRuby.GetXmlJsonStrResponse retVal = ((Bridge.AcmeRuby.clsCaltecServiceSoap)(this)).GetXmlJsonStr(inValue);
            return retVal.Body.GetXmlJsonStrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bridge.AcmeRuby.GetXmlJsonStrResponse> Bridge.AcmeRuby.clsCaltecServiceSoap.GetXmlJsonStrAsync(Bridge.AcmeRuby.GetXmlJsonStrRequest request) {
            return base.Channel.GetXmlJsonStrAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bridge.AcmeRuby.GetXmlJsonStrResponse> GetXmlJsonStrAsync(string Username, string Password, string TipoId, string Id, string xmlParameters) {
            Bridge.AcmeRuby.GetXmlJsonStrRequest inValue = new Bridge.AcmeRuby.GetXmlJsonStrRequest();
            inValue.Body = new Bridge.AcmeRuby.GetXmlJsonStrRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.TipoId = TipoId;
            inValue.Body.Id = Id;
            inValue.Body.xmlParameters = xmlParameters;
            return ((Bridge.AcmeRuby.clsCaltecServiceSoap)(this)).GetXmlJsonStrAsync(inValue);
        }
    }
}
