//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bridge.DataviewService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dvtransaction.com/", ConfigurationName="DataviewService.DataviewServiceSoap")]
    public interface DataviewServiceSoap {
        
        // CODEGEN: Generating message contract since element name PingResult from namespace http://dvtransaction.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dvtransaction.com/Ping", ReplyAction="*")]
        Bridge.DataviewService.PingResponse Ping(Bridge.DataviewService.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dvtransaction.com/Ping", ReplyAction="*")]
        System.Threading.Tasks.Task<Bridge.DataviewService.PingResponse> PingAsync(Bridge.DataviewService.PingRequest request);
        
        // CODEGEN: Generating message contract since element name LoadSystemResult from namespace http://dvtransaction.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dvtransaction.com/LoadSystem", ReplyAction="*")]
        Bridge.DataviewService.LoadSystemResponse LoadSystem(Bridge.DataviewService.LoadSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dvtransaction.com/LoadSystem", ReplyAction="*")]
        System.Threading.Tasks.Task<Bridge.DataviewService.LoadSystemResponse> LoadSystemAsync(Bridge.DataviewService.LoadSystemRequest request);
        
        // CODEGEN: Generating message contract since element name XmlRequest from namespace http://dvtransaction.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dvtransaction.com/ProcessApplication", ReplyAction="*")]
        Bridge.DataviewService.ProcessApplicationResponse ProcessApplication(Bridge.DataviewService.ProcessApplicationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dvtransaction.com/ProcessApplication", ReplyAction="*")]
        System.Threading.Tasks.Task<Bridge.DataviewService.ProcessApplicationResponse> ProcessApplicationAsync(Bridge.DataviewService.ProcessApplicationRequest request);
        
        // CODEGEN: Generating message contract since element name XmlRequest from namespace http://dvtransaction.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dvtransaction.com/ProcessApplicationXML", ReplyAction="*")]
        Bridge.DataviewService.ProcessApplicationXMLResponse ProcessApplicationXML(Bridge.DataviewService.ProcessApplicationXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dvtransaction.com/ProcessApplicationXML", ReplyAction="*")]
        System.Threading.Tasks.Task<Bridge.DataviewService.ProcessApplicationXMLResponse> ProcessApplicationXMLAsync(Bridge.DataviewService.ProcessApplicationXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ping", Namespace="http://dvtransaction.com/", Order=0)]
        public Bridge.DataviewService.PingRequestBody Body;
        
        public PingRequest() {
        }
        
        public PingRequest(Bridge.DataviewService.PingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PingRequestBody {
        
        public PingRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingResponse", Namespace="http://dvtransaction.com/", Order=0)]
        public Bridge.DataviewService.PingResponseBody Body;
        
        public PingResponse() {
        }
        
        public PingResponse(Bridge.DataviewService.PingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dvtransaction.com/")]
    public partial class PingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PingResult;
        
        public PingResponseBody() {
        }
        
        public PingResponseBody(string PingResult) {
            this.PingResult = PingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadSystemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadSystem", Namespace="http://dvtransaction.com/", Order=0)]
        public Bridge.DataviewService.LoadSystemRequestBody Body;
        
        public LoadSystemRequest() {
        }
        
        public LoadSystemRequest(Bridge.DataviewService.LoadSystemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadSystemRequestBody {
        
        public LoadSystemRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadSystemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadSystemResponse", Namespace="http://dvtransaction.com/", Order=0)]
        public Bridge.DataviewService.LoadSystemResponseBody Body;
        
        public LoadSystemResponse() {
        }
        
        public LoadSystemResponse(Bridge.DataviewService.LoadSystemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dvtransaction.com/")]
    public partial class LoadSystemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadSystemResult;
        
        public LoadSystemResponseBody() {
        }
        
        public LoadSystemResponseBody(string LoadSystemResult) {
            this.LoadSystemResult = LoadSystemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessApplicationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessApplication", Namespace="http://dvtransaction.com/", Order=0)]
        public Bridge.DataviewService.ProcessApplicationRequestBody Body;
        
        public ProcessApplicationRequest() {
        }
        
        public ProcessApplicationRequest(Bridge.DataviewService.ProcessApplicationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dvtransaction.com/")]
    public partial class ProcessApplicationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlRequest;
        
        public ProcessApplicationRequestBody() {
        }
        
        public ProcessApplicationRequestBody(string XmlRequest) {
            this.XmlRequest = XmlRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessApplicationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessApplicationResponse", Namespace="http://dvtransaction.com/", Order=0)]
        public Bridge.DataviewService.ProcessApplicationResponseBody Body;
        
        public ProcessApplicationResponse() {
        }
        
        public ProcessApplicationResponse(Bridge.DataviewService.ProcessApplicationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dvtransaction.com/")]
    public partial class ProcessApplicationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProcessApplicationResult;
        
        public ProcessApplicationResponseBody() {
        }
        
        public ProcessApplicationResponseBody(string ProcessApplicationResult) {
            this.ProcessApplicationResult = ProcessApplicationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessApplicationXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessApplicationXML", Namespace="http://dvtransaction.com/", Order=0)]
        public Bridge.DataviewService.ProcessApplicationXMLRequestBody Body;
        
        public ProcessApplicationXMLRequest() {
        }
        
        public ProcessApplicationXMLRequest(Bridge.DataviewService.ProcessApplicationXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dvtransaction.com/")]
    public partial class ProcessApplicationXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement XmlRequest;
        
        public ProcessApplicationXMLRequestBody() {
        }
        
        public ProcessApplicationXMLRequestBody(System.Xml.XmlElement XmlRequest) {
            this.XmlRequest = XmlRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessApplicationXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessApplicationXMLResponse", Namespace="http://dvtransaction.com/", Order=0)]
        public Bridge.DataviewService.ProcessApplicationXMLResponseBody Body;
        
        public ProcessApplicationXMLResponse() {
        }
        
        public ProcessApplicationXMLResponse(Bridge.DataviewService.ProcessApplicationXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dvtransaction.com/")]
    public partial class ProcessApplicationXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ProcessApplicationXMLResult;
        
        public ProcessApplicationXMLResponseBody() {
        }
        
        public ProcessApplicationXMLResponseBody(System.Xml.XmlElement ProcessApplicationXMLResult) {
            this.ProcessApplicationXMLResult = ProcessApplicationXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataviewServiceSoapChannel : Bridge.DataviewService.DataviewServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataviewServiceSoapClient : System.ServiceModel.ClientBase<Bridge.DataviewService.DataviewServiceSoap>, Bridge.DataviewService.DataviewServiceSoap {
        
        public DataviewServiceSoapClient() {
        }
        
        public DataviewServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataviewServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataviewServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataviewServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bridge.DataviewService.PingResponse Bridge.DataviewService.DataviewServiceSoap.Ping(Bridge.DataviewService.PingRequest request) {
            return base.Channel.Ping(request);
        }
        
        public string Ping() {
            Bridge.DataviewService.PingRequest inValue = new Bridge.DataviewService.PingRequest();
            inValue.Body = new Bridge.DataviewService.PingRequestBody();
            Bridge.DataviewService.PingResponse retVal = ((Bridge.DataviewService.DataviewServiceSoap)(this)).Ping(inValue);
            return retVal.Body.PingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bridge.DataviewService.PingResponse> Bridge.DataviewService.DataviewServiceSoap.PingAsync(Bridge.DataviewService.PingRequest request) {
            return base.Channel.PingAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bridge.DataviewService.PingResponse> PingAsync() {
            Bridge.DataviewService.PingRequest inValue = new Bridge.DataviewService.PingRequest();
            inValue.Body = new Bridge.DataviewService.PingRequestBody();
            return ((Bridge.DataviewService.DataviewServiceSoap)(this)).PingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bridge.DataviewService.LoadSystemResponse Bridge.DataviewService.DataviewServiceSoap.LoadSystem(Bridge.DataviewService.LoadSystemRequest request) {
            return base.Channel.LoadSystem(request);
        }
        
        public string LoadSystem() {
            Bridge.DataviewService.LoadSystemRequest inValue = new Bridge.DataviewService.LoadSystemRequest();
            inValue.Body = new Bridge.DataviewService.LoadSystemRequestBody();
            Bridge.DataviewService.LoadSystemResponse retVal = ((Bridge.DataviewService.DataviewServiceSoap)(this)).LoadSystem(inValue);
            return retVal.Body.LoadSystemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bridge.DataviewService.LoadSystemResponse> Bridge.DataviewService.DataviewServiceSoap.LoadSystemAsync(Bridge.DataviewService.LoadSystemRequest request) {
            return base.Channel.LoadSystemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bridge.DataviewService.LoadSystemResponse> LoadSystemAsync() {
            Bridge.DataviewService.LoadSystemRequest inValue = new Bridge.DataviewService.LoadSystemRequest();
            inValue.Body = new Bridge.DataviewService.LoadSystemRequestBody();
            return ((Bridge.DataviewService.DataviewServiceSoap)(this)).LoadSystemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bridge.DataviewService.ProcessApplicationResponse Bridge.DataviewService.DataviewServiceSoap.ProcessApplication(Bridge.DataviewService.ProcessApplicationRequest request) {
            return base.Channel.ProcessApplication(request);
        }
        
        public string ProcessApplication(string XmlRequest) {
            Bridge.DataviewService.ProcessApplicationRequest inValue = new Bridge.DataviewService.ProcessApplicationRequest();
            inValue.Body = new Bridge.DataviewService.ProcessApplicationRequestBody();
            inValue.Body.XmlRequest = XmlRequest;
            Bridge.DataviewService.ProcessApplicationResponse retVal = ((Bridge.DataviewService.DataviewServiceSoap)(this)).ProcessApplication(inValue);
            return retVal.Body.ProcessApplicationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bridge.DataviewService.ProcessApplicationResponse> Bridge.DataviewService.DataviewServiceSoap.ProcessApplicationAsync(Bridge.DataviewService.ProcessApplicationRequest request) {
            return base.Channel.ProcessApplicationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bridge.DataviewService.ProcessApplicationResponse> ProcessApplicationAsync(string XmlRequest) {
            Bridge.DataviewService.ProcessApplicationRequest inValue = new Bridge.DataviewService.ProcessApplicationRequest();
            inValue.Body = new Bridge.DataviewService.ProcessApplicationRequestBody();
            inValue.Body.XmlRequest = XmlRequest;
            return ((Bridge.DataviewService.DataviewServiceSoap)(this)).ProcessApplicationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bridge.DataviewService.ProcessApplicationXMLResponse Bridge.DataviewService.DataviewServiceSoap.ProcessApplicationXML(Bridge.DataviewService.ProcessApplicationXMLRequest request) {
            return base.Channel.ProcessApplicationXML(request);
        }
        
        public System.Xml.XmlElement ProcessApplicationXML(System.Xml.XmlElement XmlRequest) {
            Bridge.DataviewService.ProcessApplicationXMLRequest inValue = new Bridge.DataviewService.ProcessApplicationXMLRequest();
            inValue.Body = new Bridge.DataviewService.ProcessApplicationXMLRequestBody();
            inValue.Body.XmlRequest = XmlRequest;
            Bridge.DataviewService.ProcessApplicationXMLResponse retVal = ((Bridge.DataviewService.DataviewServiceSoap)(this)).ProcessApplicationXML(inValue);
            return retVal.Body.ProcessApplicationXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bridge.DataviewService.ProcessApplicationXMLResponse> Bridge.DataviewService.DataviewServiceSoap.ProcessApplicationXMLAsync(Bridge.DataviewService.ProcessApplicationXMLRequest request) {
            return base.Channel.ProcessApplicationXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bridge.DataviewService.ProcessApplicationXMLResponse> ProcessApplicationXMLAsync(System.Xml.XmlElement XmlRequest) {
            Bridge.DataviewService.ProcessApplicationXMLRequest inValue = new Bridge.DataviewService.ProcessApplicationXMLRequest();
            inValue.Body = new Bridge.DataviewService.ProcessApplicationXMLRequestBody();
            inValue.Body.XmlRequest = XmlRequest;
            return ((Bridge.DataviewService.DataviewServiceSoap)(this)).ProcessApplicationXMLAsync(inValue);
        }
    }
}
