//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pecuniaus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pecuniaus.Resources.ApplicationMessages", typeof(ApplicationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business processor information could not be updated.
        /// </summary>
        public static string MPBusinessProcessorUpdateFailure {
            get {
                return ResourceManager.GetString("MPBusinessProcessorUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business processor information updated successfully.
        /// </summary>
        public static string MPBusinessProcessorUpdateSuccess {
            get {
                return ResourceManager.GetString("MPBusinessProcessorUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business information could not be updated.
        /// </summary>
        public static string MPBusinessUpdateFailure {
            get {
                return ResourceManager.GetString("MPBusinessUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business information updated successfully.
        /// </summary>
        public static string MPBusinessUpdateSuccess {
            get {
                return ResourceManager.GetString("MPBusinessUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information could not be added.
        /// </summary>
        public static string MPContactAddFailure {
            get {
                return ResourceManager.GetString("MPContactAddFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information added successfully.
        /// </summary>
        public static string MPContactAddSuccess {
            get {
                return ResourceManager.GetString("MPContactAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information could not be updated.
        /// </summary>
        public static string MPContactUpdateFailure {
            get {
                return ResourceManager.GetString("MPContactUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information updated successfully.
        /// </summary>
        public static string MPContactUpdateSuccess {
            get {
                return ResourceManager.GetString("MPContactUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract General Information could not be updated.
        /// </summary>
        public static string MPContractGeneralInfoUpdateFailure {
            get {
                return ResourceManager.GetString("MPContractGeneralInfoUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract General Information updated successfully.
        /// </summary>
        public static string MPContractGeneralInfoUpdateSuccess {
            get {
                return ResourceManager.GetString("MPContractGeneralInfoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Sales Rep Information could not be added.
        /// </summary>
        public static string MPContractSalesRepAddFailure {
            get {
                return ResourceManager.GetString("MPContractSalesRepAddFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Sales Rep Information added successfully.
        /// </summary>
        public static string MPContractSalesRepAddSuccess {
            get {
                return ResourceManager.GetString("MPContractSalesRepAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Sales Rep Information could not be updated.
        /// </summary>
        public static string MPContractSalesRepUpdateFailure {
            get {
                return ResourceManager.GetString("MPContractSalesRepUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Sales Rep Information updated successfully.
        /// </summary>
        public static string MPContractSalesRepUpdateSuccess {
            get {
                return ResourceManager.GetString("MPContractSalesRepUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document upload failed.
        /// </summary>
        public static string MPDocumentUploadFailure {
            get {
                return ResourceManager.GetString("MPDocumentUploadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document uploaded successfully.
        /// </summary>
        public static string MPDocumentUploadSuccess {
            get {
                return ResourceManager.GetString("MPDocumentUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord information could not be updated.
        /// </summary>
        public static string MPLandlordUpdateFailure {
            get {
                return ResourceManager.GetString("MPLandlordUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord information updated successfully.
        /// </summary>
        public static string MPLandlordUpdateSuccess {
            get {
                return ResourceManager.GetString("MPLandlordUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner information could not be added.
        /// </summary>
        public static string MPOwnerAddFailure {
            get {
                return ResourceManager.GetString("MPOwnerAddFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner information added successfully.
        /// </summary>
        public static string MPOwnerAddSuccess {
            get {
                return ResourceManager.GetString("MPOwnerAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner information could not be updated.
        /// </summary>
        public static string MPOwnerUpdateFailure {
            get {
                return ResourceManager.GetString("MPOwnerUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner information updated successfully.
        /// </summary>
        public static string MPOwnerUpdateSuccess {
            get {
                return ResourceManager.GetString("MPOwnerUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile information could not be updated.
        /// </summary>
        public static string MPProfileUpdateFailure {
            get {
                return ResourceManager.GetString("MPProfileUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile information updated successfully.
        /// </summary>
        public static string MPProfileUpdateSuccess {
            get {
                return ResourceManager.GetString("MPProfileUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement email sent successfully.
        /// </summary>
        public static string MPStatementEmailSuccess {
            get {
                return ResourceManager.GetString("MPStatementEmailSuccess", resourceCulture);
            }
        }
    }
}
