//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pecuniaus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pecuniaus.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Contracts.
        /// </summary>
        public static string ActiveContracts {
            get {
                return ResourceManager.GetString("ActiveContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Manual MCCV.
        /// </summary>
        public static string AddManualMCCV {
            get {
                return ResourceManager.GetString("AddManualMCCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        public static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Expenses.
        /// </summary>
        public static string AdministrativeExpenses {
            get {
                return ResourceManager.GetString("AdministrativeExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliations.
        /// </summary>
        public static string Affiliations {
            get {
                return ResourceManager.GetString("Affiliations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Sales Rep.
        /// </summary>
        public static string AssignedSalesRep {
            get {
                return ResourceManager.GetString("AssignedSalesRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Info Verification.
        /// </summary>
        public static string BankInfoVerification {
            get {
                return ResourceManager.GetString("BankInfoVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLA.
        /// </summary>
        public static string BLA {
            get {
                return ResourceManager.GetString("BLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Information.
        /// </summary>
        public static string BusinessInformation {
            get {
                return ResourceManager.GetString("BusinessInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        public static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellPhone.
        /// </summary>
        public static string CellPhone {
            get {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        public static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Name Verification.
        /// </summary>
        public static string CommercialnameVerification {
            get {
                return ResourceManager.GetString("CommercialnameVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract ID.
        /// </summary>
        public static string ContractID {
            get {
                return ResourceManager.GetString("ContractID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Status.
        /// </summary>
        public static string ContractStatus {
            get {
                return ResourceManager.GetString("ContractStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Workflow.
        /// </summary>
        public static string ContractWorkflow {
            get {
                return ResourceManager.GetString("ContractWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corp Doc. Verification.
        /// </summary>
        public static string CorpDocVerification {
            get {
                return ResourceManager.GetString("CorpDocVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Reports.
        /// </summary>
        public static string CreditReports {
            get {
                return ResourceManager.GetString("CreditReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Information Verification.
        /// </summary>
        public static string CWBankInformationVerification {
            get {
                return ResourceManager.GetString("CWBankInformationVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Name Verification.
        /// </summary>
        public static string CWCommercialNameVerification {
            get {
                return ResourceManager.GetString("CWCommercialNameVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string CWContract {
            get {
                return ResourceManager.GetString("CWContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Documents Verification.
        /// </summary>
        public static string CWCorporateDocumentsVerification {
            get {
                return ResourceManager.GetString("CWCorporateDocumentsVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Enty.
        /// </summary>
        public static string CWDataEntry {
            get {
                return ResourceManager.GetString("CWDataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding.
        /// </summary>
        public static string CWFunding {
            get {
                return ResourceManager.GetString("CWFunding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord Verification.
        /// </summary>
        public static string CWLandlordVerification {
            get {
                return ResourceManager.GetString("CWLandlordVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string CWReview {
            get {
                return ResourceManager.GetString("CWReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Document.
        /// </summary>
        public static string CWScanDocument {
            get {
                return ResourceManager.GetString("CWScanDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Call.
        /// </summary>
        public static string CWVerificationCall {
            get {
                return ResourceManager.GetString("CWVerificationCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Task.
        /// </summary>
        public static string CWVerificationTask {
            get {
                return ResourceManager.GetString("CWVerificationTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Entry.
        /// </summary>
        public static string DataEntry {
            get {
                return ResourceManager.GetString("DataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline Note.
        /// </summary>
        public static string DeclineNote {
            get {
                return ResourceManager.GetString("DeclineNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline Reason.
        /// </summary>
        public static string DeclineReason {
            get {
                return ResourceManager.GetString("DeclineReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Scanning.
        /// </summary>
        public static string DocumentScanning {
            get {
                return ResourceManager.GetString("DocumentScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string Dollar {
            get {
                return ResourceManager.GetString("Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient List.
        /// </summary>
        public static string EmailRecipient {
            get {
                return ResourceManager.GetString("EmailRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience the lessor.
        /// </summary>
        public static string Experiencethelessor {
            get {
                return ResourceManager.GetString("Experiencethelessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string ExporttoExcel {
            get {
                return ResourceManager.GetString("ExporttoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        public static string Final {
            get {
                return ResourceManager.GetString("Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Validation.
        /// </summary>
        public static string FinalValidation {
            get {
                return ResourceManager.GetString("FinalValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding.
        /// </summary>
        public static string Funding {
            get {
                return ResourceManager.GetString("Funding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate BLA.
        /// </summary>
        public static string GenerateBLA {
            get {
                return ResourceManager.GetString("GenerateBLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Contract.
        /// </summary>
        public static string GenerateContract {
            get {
                return ResourceManager.GetString("GenerateContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate IOU.
        /// </summary>
        public static string GenerateIOU {
            get {
                return ResourceManager.GetString("GenerateIOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genrate Score.
        /// </summary>
        public static string GenrateScore {
            get {
                return ResourceManager.GetString("GenrateScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kickback.
        /// </summary>
        public static string Kickback {
            get {
                return ResourceManager.GetString("Kickback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LandLord.
        /// </summary>
        public static string LandLord {
            get {
                return ResourceManager.GetString("LandLord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord Experience.
        /// </summary>
        public static string LandlordExperience {
            get {
                return ResourceManager.GetString("LandlordExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LandLord Verification.
        /// </summary>
        public static string LandLordVerification {
            get {
                return ResourceManager.GetString("LandLordVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Address.
        /// </summary>
        public static string LegalAddress {
            get {
                return ResourceManager.GetString("LegalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Document.
        /// </summary>
        public static string LegalDocument {
            get {
                return ResourceManager.GetString("LegalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Name.
        /// </summary>
        public static string LegalName {
            get {
                return ResourceManager.GetString("LegalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaned Amount.
        /// </summary>
        public static string LoanedAmount {
            get {
                return ResourceManager.GetString("LoanedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCA Amount.
        /// </summary>
        public static string MCAAmount {
            get {
                return ResourceManager.GetString("MCAAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Credit Card Volumes.
        /// </summary>
        public static string MCCV {
            get {
                return ResourceManager.GetString("MCCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Credit Card Volumes.
        /// </summary>
        public static string MCCVHeader {
            get {
                return ResourceManager.GetString("MCCVHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant.
        /// </summary>
        public static string Merchant {
            get {
                return ResourceManager.GetString("Merchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant ID.
        /// </summary>
        public static string MerchantID {
            get {
                return ResourceManager.GetString("MerchantID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Information.
        /// </summary>
        public static string MerchantInformation {
            get {
                return ResourceManager.GetString("MerchantInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Name.
        /// </summary>
        public static string MerchantName {
            get {
                return ResourceManager.GetString("MerchantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Profile.
        /// </summary>
        public static string MerchantProfile {
            get {
                return ResourceManager.GetString("MerchantProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Review.
        /// </summary>
        public static string MerchantReview {
            get {
                return ResourceManager.GetString("MerchantReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Evaluation.
        /// </summary>
        public static string MerchatEvaluation {
            get {
                return ResourceManager.GetString("MerchatEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Reports.
        /// </summary>
        public static string NoReports {
            get {
                return ResourceManager.GetString("NoReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Text.
        /// </summary>
        public static string NoteText {
            get {
                return ResourceManager.GetString("NoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Type ID.
        /// </summary>
        public static string NoteTypeID {
            get {
                return ResourceManager.GetString("NoteTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Accptance.
        /// </summary>
        public static string OfferAccptance {
            get {
                return ResourceManager.GetString("OfferAccptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Creation.
        /// </summary>
        public static string OfferCreation {
            get {
                return ResourceManager.GetString("OfferCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owed Amount.
        /// </summary>
        public static string OwnedAmount {
            get {
                return ResourceManager.GetString("OwnedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners.
        /// </summary>
        public static string Owners {
            get {
                return ResourceManager.GetString("Owners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        public static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Agreement.
        /// </summary>
        public static string PaymentAgreement {
            get {
                return ResourceManager.GetString("PaymentAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Address.
        /// </summary>
        public static string PhysicalAddress {
            get {
                return ResourceManager.GetString("PhysicalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Entry.
        /// </summary>
        public static string PQDataEntry {
            get {
                return ResourceManager.GetString("PQDataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Evaluation.
        /// </summary>
        public static string PQMerchantEvaluation {
            get {
                return ResourceManager.GetString("PQMerchantEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Credit Card Volumes.
        /// </summary>
        public static string PQMonthlyCreditCardVolumes {
            get {
                return ResourceManager.GetString("PQMonthlyCreditCardVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Acceptance.
        /// </summary>
        public static string PQOfferAcceptance {
            get {
                return ResourceManager.GetString("PQOfferAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Creation.
        /// </summary>
        public static string PQOfferCreation {
            get {
                return ResourceManager.GetString("PQOfferCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Document.
        /// </summary>
        public static string PQScanDocument {
            get {
                return ResourceManager.GetString("PQScanDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prequal Workflow.
        /// </summary>
        public static string Prequal {
            get {
                return ResourceManager.GetString("Prequal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prequal Workflow.
        /// </summary>
        public static string PrequalWorkflow {
            get {
                return ResourceManager.GetString("PrequalWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Information.
        /// </summary>
        public static string ProcessorInformation {
            get {
                return ResourceManager.GetString("ProcessorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proportion.
        /// </summary>
        public static string Proportion {
            get {
                return ResourceManager.GetString("Proportion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Credit Reports.
        /// </summary>
        public static string PullCreditReports {
            get {
                return ResourceManager.GetString("PullCreditReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention.
        /// </summary>
        public static string Retention {
            get {
                return ResourceManager.GetString("Retention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Task.
        /// </summary>
        public static string ReviewTask {
            get {
                return ResourceManager.GetString("ReviewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Evaluation.
        /// </summary>
        public static string RiskEvaluation {
            get {
                return ResourceManager.GetString("RiskEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNC.
        /// </summary>
        public static string RNC {
            get {
                return ResourceManager.GetString("RNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robert Ryan.
        /// </summary>
        public static string RobertRyan {
            get {
                return ResourceManager.GetString("RobertRyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ryan.
        /// </summary>
        public static string Ryan {
            get {
                return ResourceManager.GetString("Ryan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Rep.
        /// </summary>
        public static string SaleRep {
            get {
                return ResourceManager.GetString("SaleRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Send.
        /// </summary>
        public static string SaveandSend {
            get {
                return ResourceManager.GetString("SaveandSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Note.
        /// </summary>
        public static string SaveNote {
            get {
                return ResourceManager.GetString("SaveNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Document.
        /// </summary>
        public static string ScanDocument {
            get {
                return ResourceManager.GetString("ScanDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        public static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores.
        /// </summary>
        public static string Scores {
            get {
                return ResourceManager.GetString("Scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring Data.
        /// </summary>
        public static string ScoringData {
            get {
                return ResourceManager.GetString("ScoringData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request for Funding.
        /// </summary>
        public static string SendRequestforFunding {
            get {
                return ResourceManager.GetString("SendRequestforFunding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN.
        /// </summary>
        public static string SSN {
            get {
                return ResourceManager.GetString("SSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statements.
        /// </summary>
        public static string Statements {
            get {
                return ResourceManager.GetString("Statements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        public static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Documents.
        /// </summary>
        public static string UploadDocuments {
            get {
                return ResourceManager.GetString("UploadDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        public static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Call.
        /// </summary>
        public static string VerificationCall {
            get {
                return ResourceManager.GetString("VerificationCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Task.
        /// </summary>
        public static string VerificationTask {
            get {
                return ResourceManager.GetString("VerificationTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Call.
        /// </summary>
        public static string WelcomeCall {
            get {
                return ResourceManager.GetString("WelcomeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong.
        /// </summary>
        public static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
