//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pecuniaus.Resources.User {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TaskManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskManagement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pecuniaus.Resources.User.TaskManagement", typeof(TaskManagement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Date.
        /// </summary>
        public static string AssignedDate {
            get {
                return ResourceManager.GetString("AssignedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To.
        /// </summary>
        public static string AssignedTo {
            get {
                return ResourceManager.GetString("AssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWContract.
        /// </summary>
        public static string CWContract {
            get {
                return ResourceManager.GetString("CWContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWDataEntry.
        /// </summary>
        public static string CWDataEntry {
            get {
                return ResourceManager.GetString("CWDataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWFinalValidation.
        /// </summary>
        public static string CWFinalValidation {
            get {
                return ResourceManager.GetString("CWFinalValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWFunding.
        /// </summary>
        public static string CWFunding {
            get {
                return ResourceManager.GetString("CWFunding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWReview.
        /// </summary>
        public static string CWReview {
            get {
                return ResourceManager.GetString("CWReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWScanDocument.
        /// </summary>
        public static string CWScanDocument {
            get {
                return ResourceManager.GetString("CWScanDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWVerificationCall.
        /// </summary>
        public static string CWVerificationCall {
            get {
                return ResourceManager.GetString("CWVerificationCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWVerificationTask.
        /// </summary>
        public static string CWVerificationTask {
            get {
                return ResourceManager.GetString("CWVerificationTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Name.
        /// </summary>
        public static string MerchantName {
            get {
                return ResourceManager.GetString("MerchantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PQDataEntry.
        /// </summary>
        public static string PQDataEntry {
            get {
                return ResourceManager.GetString("PQDataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PQMerchantEvaluation.
        /// </summary>
        public static string PQMerchantEvaluation {
            get {
                return ResourceManager.GetString("PQMerchantEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PQMerchantReview.
        /// </summary>
        public static string PQMerchantReview {
            get {
                return ResourceManager.GetString("PQMerchantReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PQMonthlyCreditCardVolumes.
        /// </summary>
        public static string PQMonthlyCreditCardVolumes {
            get {
                return ResourceManager.GetString("PQMonthlyCreditCardVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PQOfferAcceptance.
        /// </summary>
        public static string PQOfferAcceptance {
            get {
                return ResourceManager.GetString("PQOfferAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PQOfferCreation.
        /// </summary>
        public static string PQOfferCreation {
            get {
                return ResourceManager.GetString("PQOfferCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PQScanDocument.
        /// </summary>
        public static string PQScanDocument {
            get {
                return ResourceManager.GetString("PQScanDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWContract.
        /// </summary>
        public static string RWContract {
            get {
                return ResourceManager.GetString("RWContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWDocumentVerification.
        /// </summary>
        public static string RWDocumentVerification {
            get {
                return ResourceManager.GetString("RWDocumentVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWFinalValidation.
        /// </summary>
        public static string RWFinalValidation {
            get {
                return ResourceManager.GetString("RWFinalValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWFunding.
        /// </summary>
        public static string RWFunding {
            get {
                return ResourceManager.GetString("RWFunding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWListofmerchants.
        /// </summary>
        public static string RWListofmerchants {
            get {
                return ResourceManager.GetString("RWListofmerchants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWMerchantEvaluation.
        /// </summary>
        public static string RWMerchantEvaluation {
            get {
                return ResourceManager.GetString("RWMerchantEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWOfferCreation.
        /// </summary>
        public static string RWOfferCreation {
            get {
                return ResourceManager.GetString("RWOfferCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWRenewalReview.
        /// </summary>
        public static string RWRenewalReview {
            get {
                return ResourceManager.GetString("RWRenewalReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Name.
        /// </summary>
        public static string StatusName {
            get {
                return ResourceManager.GetString("StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Management.
        /// </summary>
        public static string TaskManagementMenuName {
            get {
                return ResourceManager.GetString("TaskManagementMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        public static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
