//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pecuniaus.Resources.Collection {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Collection {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Collection() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pecuniaus.Resources.Collection.Collection", typeof(Collection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Contracts.
        /// </summary>
        public static string ActiveContracts {
            get {
                return ResourceManager.GetString("ActiveContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AEC.
        /// </summary>
        public static string AEC {
            get {
                return ResourceManager.GetString("AEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AEC &lt;br&gt; Amount.
        /// </summary>
        public static string AECAmount {
            get {
                return ResourceManager.GetString("AECAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliation.
        /// </summary>
        public static string Affiliation {
            get {
                return ResourceManager.GetString("Affiliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliations.
        /// </summary>
        public static string Affiliations {
            get {
                return ResourceManager.GetString("Affiliations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to assign Lawyer?.
        /// </summary>
        public static string AreyousuretoassignnewLawyer {
            get {
                return ResourceManager.GetString("AreyousuretoassignnewLawyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Lawyers.
        /// </summary>
        public static string AssignedLawyers {
            get {
                return ResourceManager.GetString("AssignedLawyers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign New Lawyer.
        /// </summary>
        public static string AssignNewLawyer {
            get {
                return ResourceManager.GetString("AssignNewLawyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average CC Sales.
        /// </summary>
        public static string AverageCC {
            get {
                return ResourceManager.GetString("AverageCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average CC &lt;br&gt;used in Offer.
        /// </summary>
        public static string AverageCCSalesUser {
            get {
                return ResourceManager.GetString("AverageCCSalesUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to cancel all the changes?.
        /// </summary>
        public static string CancelChanges {
            get {
                return ResourceManager.GetString("CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Average used in Offer.
        /// </summary>
        public static string CCAverageusedinOffer {
            get {
                return ResourceManager.GetString("CCAverageusedinOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Activity saved successfully.
        /// </summary>
        public static string CollectionActivities {
            get {
                return ResourceManager.GetString("CollectionActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        public static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection State.
        /// </summary>
        public static string CollectionState {
            get {
                return ResourceManager.GetString("CollectionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Status.
        /// </summary>
        public static string CollectionStatus {
            get {
                return ResourceManager.GetString("CollectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string CollectionTitle {
            get {
                return ResourceManager.GetString("CollectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections Workflow.
        /// </summary>
        public static string CollectionWorkflow {
            get {
                return ResourceManager.GetString("CollectionWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Id.
        /// </summary>
        public static string ContractId {
            get {
                return ResourceManager.GetString("ContractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New/Edit Lawyer.
        /// </summary>
        public static string CreateNewLawyer {
            get {
                return ResourceManager.GetString("CreateNewLawyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while Credit Report pulled.
        /// </summary>
        public static string CreditReportError {
            get {
                return ResourceManager.GetString("CreditReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Report pulled successfully.
        /// </summary>
        public static string CreditReportPulled {
            get {
                return ResourceManager.GetString("CreditReportPulled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Credito.
        /// </summary>
        public static string DataCredito {
            get {
                return ResourceManager.GetString("DataCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Assignment.
        /// </summary>
        public static string DateOfAssignment {
            get {
                return ResourceManager.GetString("DateOfAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day without &lt;br&gt;activity.
        /// </summary>
        public static string DayWithoutActivity {
            get {
                return ResourceManager.GetString("DayWithoutActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete Merchant Document(s)?.
        /// </summary>
        public static string DeleteMerchantDocument {
            get {
                return ResourceManager.GetString("DeleteMerchantDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document ID.
        /// </summary>
        public static string DocumentId {
            get {
                return ResourceManager.GetString("DocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Name.
        /// </summary>
        public static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Updated successfully.
        /// </summary>
        public static string DocumentUpdated {
            get {
                return ResourceManager.GetString("DocumentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while uploading the Document.
        /// </summary>
        public static string ErrorDocumentUpdated {
            get {
                return ResourceManager.GetString("ErrorDocumentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload payment receipt document.
        /// </summary>
        public static string ErrorNotifyPayment {
            get {
                return ResourceManager.GetString("ErrorNotifyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload payment agreement documnet.
        /// </summary>
        public static string ErrorPaymentAgreement {
            get {
                return ResourceManager.GetString("ErrorPaymentAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected.
        /// </summary>
        public static string Expected {
            get {
                return ResourceManager.GetString("Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Date.
        /// </summary>
        public static string ExpectedDate {
            get {
                return ResourceManager.GetString("ExpectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding &lt;br&gt; Date.
        /// </summary>
        public static string FundingDate {
            get {
                return ResourceManager.GetString("FundingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Letter.
        /// </summary>
        public static string GenerateLetter {
            get {
                return ResourceManager.GetString("GenerateLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Contracts.
        /// </summary>
        public static string InactiveContracts {
            get {
                return ResourceManager.GetString("InactiveContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord.
        /// </summary>
        public static string Landlord {
            get {
                return ResourceManager.GetString("Landlord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Answers can not be modified from here).
        /// </summary>
        public static string LandLordAnswers {
            get {
                return ResourceManager.GetString("LandLordAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord updated successfully.
        /// </summary>
        public static string LandlordUpdated {
            get {
                return ResourceManager.GetString("LandlordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Date of Evaluation.
        /// </summary>
        public static string LastDateofEvaluation {
            get {
                return ResourceManager.GetString("LastDateofEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawyer added/updated successfully.
        /// </summary>
        public static string LawyerAdded {
            get {
                return ResourceManager.GetString("LawyerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawyer assigned successfully.
        /// </summary>
        public static string LawyerAssigned {
            get {
                return ResourceManager.GetString("LawyerAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawyer Company.
        /// </summary>
        public static string LawyerCompany {
            get {
                return ResourceManager.GetString("LawyerCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawyer First Name.
        /// </summary>
        public static string LawyerFirstName {
            get {
                return ResourceManager.GetString("LawyerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawyer Last Name.
        /// </summary>
        public static string LawyerLastName {
            get {
                return ResourceManager.GetString("LawyerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Date.
        /// </summary>
        public static string lbFundingDate {
            get {
                return ResourceManager.GetString("lbFundingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owed Amount.
        /// </summary>
        public static string lbOwnedAmount {
            get {
                return ResourceManager.GetString("lbOwnedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Amount.
        /// </summary>
        public static string lbPendingAmount {
            get {
                return ResourceManager.GetString("lbPendingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        public static string Legal {
            get {
                return ResourceManager.GetString("Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        public static string Letter {
            get {
                return ResourceManager.GetString("Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant.
        /// </summary>
        public static string Merchant {
            get {
                return ResourceManager.GetString("Merchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant affiliations.
        /// </summary>
        public static string MerchantAffiliations {
            get {
                return ResourceManager.GetString("MerchantAffiliations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Documents.
        /// </summary>
        public static string MerchantDocuments {
            get {
                return ResourceManager.GetString("MerchantDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Document(s) deleted successfully.
        /// </summary>
        public static string MerchantDocumentsDeleted {
            get {
                return ResourceManager.GetString("MerchantDocumentsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting Merchant Document(s).
        /// </summary>
        public static string MerchantDocumentsDeletedError {
            get {
                return ResourceManager.GetString("MerchantDocumentsDeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Id.
        /// </summary>
        public static string MerchantID {
            get {
                return ResourceManager.GetString("MerchantID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant &lt;br&gt; Name.
        /// </summary>
        public static string MerchantName {
            get {
                return ResourceManager.GetString("MerchantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant &lt;br&gt; Status.
        /// </summary>
        public static string MerchantStatus {
            get {
                return ResourceManager.GetString("MerchantStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly CC Average.
        /// </summary>
        public static string MonthlyCCAverage {
            get {
                return ResourceManager.GetString("MonthlyCCAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Document is selected.
        /// </summary>
        public static string NoDocumentSelected {
            get {
                return ResourceManager.GetString("NoDocumentSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Lawyer is selected.
        /// </summary>
        public static string NoLawyerSelected {
            get {
                return ResourceManager.GetString("NoLawyerSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Merchant Document is selected.
        /// </summary>
        public static string NoMerchantDocumentSelected {
            get {
                return ResourceManager.GetString("NoMerchantDocumentSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owed &lt;br&gt; Amount.
        /// </summary>
        public static string OwnedAmount {
            get {
                return ResourceManager.GetString("OwnedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending &lt;br&gt; Amount.
        /// </summary>
        public static string PendingAmount {
            get {
                return ResourceManager.GetString("PendingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select credit pull type.
        /// </summary>
        public static string PleaseSelectCreditPullType {
            get {
                return ResourceManager.GetString("PleaseSelectCreditPullType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevention.
        /// </summary>
        public static string Prevention {
            get {
                return ResourceManager.GetString("Prevention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Credit Report.
        /// </summary>
        public static string PullCreditReport {
            get {
                return ResourceManager.GetString("PullCreditReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real turn.
        /// </summary>
        public static string Realturn {
            get {
                return ResourceManager.GetString("Realturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested CC Volumes.
        /// </summary>
        public static string RequestedCCVolumes {
            get {
                return ResourceManager.GetString("RequestedCCVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Processor.
        /// </summary>
        public static string RequestProcessor {
            get {
                return ResourceManager.GetString("RequestProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention.
        /// </summary>
        public static string Retention {
            get {
                return ResourceManager.GetString("Retention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention &lt;br&gt; Time.
        /// </summary>
        public static string RetentionTime {
            get {
                return ResourceManager.GetString("RetentionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Collection Screen.
        /// </summary>
        public static string ReturnToCollectionScreen {
            get {
                return ResourceManager.GetString("ReturnToCollectionScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To Legal Screen.
        /// </summary>
        public static string ReturnToLegalScreen {
            get {
                return ResourceManager.GetString("ReturnToLegalScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Search Screen.
        /// </summary>
        public static string ReturnToSearchScreen {
            get {
                return ResourceManager.GetString("ReturnToSearchScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNC.
        /// </summary>
        public static string RNC {
            get {
                return ResourceManager.GetString("RNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show merchants paying slower than.
        /// </summary>
        public static string ShowMerchantsPayingSlowerThan {
            get {
                return ResourceManager.GetString("ShowMerchantsPayingSlowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show merchant that haven&apos;t processed in.
        /// </summary>
        public static string ShowMerchantThatHavnotProcessedIn {
            get {
                return ResourceManager.GetString("ShowMerchantThatHavnotProcessedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded By.
        /// </summary>
        public static string UploadedBy {
            get {
                return ResourceManager.GetString("UploadedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded Date.
        /// </summary>
        public static string UploadedDate {
            get {
                return ResourceManager.GetString("UploadedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Document.
        /// </summary>
        public static string ViewDocument {
            get {
                return ResourceManager.GetString("ViewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Status.
        /// </summary>
        public static string VolumeStatus {
            get {
                return ResourceManager.GetString("VolumeStatus", resourceCulture);
            }
        }
    }
}
