//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pecuniaus.Resources.MerchantProfile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Business {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Business() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pecuniaus.Resources.MerchantProfile.Business", typeof(Business).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliation Number.
        /// </summary>
        public static string AffiliationNumber {
            get {
                return ResourceManager.GetString("AffiliationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Business Started.
        /// </summary>
        public static string BusinessStartDate {
            get {
                return ResourceManager.GetString("BusinessStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Status.
        /// </summary>
        public static string BusinessStatus {
            get {
                return ResourceManager.GetString("BusinessStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string Cellphone {
            get {
                return ResourceManager.GetString("Cellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Id.
        /// </summary>
        public static string ContractId {
            get {
                return ResourceManager.GetString("ContractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Status.
        /// </summary>
        public static string ContractStatus {
            get {
                return ResourceManager.GetString("ContractStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date the business started accepting CC.
        /// </summary>
        public static string CreditCardBeginDate {
            get {
                return ResourceManager.GetString("CreditCardBeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Processed Date.
        /// </summary>
        public static string EditProcessorFirstProcessedDate {
            get {
                return ResourceManager.GetString("EditProcessorFirstProcessedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Grace Period.
        /// </summary>
        public static string EditProcessorGracePeriod {
            get {
                return ResourceManager.GetString("EditProcessorGracePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndustryType.
        /// </summary>
        public static string EditProcessorIndustryType {
            get {
                return ResourceManager.GetString("EditProcessorIndustryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Name.
        /// </summary>
        public static string EditProcessorName {
            get {
                return ResourceManager.GetString("EditProcessorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Number.
        /// </summary>
        public static string EditProcessorNumber {
            get {
                return ResourceManager.GetString("EditProcessorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        public static string EditProcessorTerminal {
            get {
                return ResourceManager.GetString("EditProcessorTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCA Amount.
        /// </summary>
        public static string LoanedAmount {
            get {
                return ResourceManager.GetString("LoanedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant ID.
        /// </summary>
        public static string MerchantID {
            get {
                return ResourceManager.GetString("MerchantID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string MerchantStatus {
            get {
                return ResourceManager.GetString("MerchantStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the business.
        /// </summary>
        public static string NameofBusiness {
            get {
                return ResourceManager.GetString("NameofBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Company.
        /// </summary>
        public static string NameofCompany {
            get {
                return ResourceManager.GetString("NameofCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owed Amount.
        /// </summary>
        public static string OwnedAmount {
            get {
                return ResourceManager.GetString("OwnedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        public static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ProcessorEdit {
            get {
                return ResourceManager.GetString("ProcessorEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Processed Date.
        /// </summary>
        public static string ProcessorFirstProcessedDate {
            get {
                return ResourceManager.GetString("ProcessorFirstProcessedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Type.
        /// </summary>
        public static string ProcessorIndustryType {
            get {
                return ResourceManager.GetString("ProcessorIndustryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Name.
        /// </summary>
        public static string ProcessorName {
            get {
                return ResourceManager.GetString("ProcessorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Number.
        /// </summary>
        public static string ProcessorNumber {
            get {
                return ResourceManager.GetString("ProcessorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string ProcessorPhoneNumber {
            get {
                return ResourceManager.GetString("ProcessorPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminals.
        /// </summary>
        public static string ProcessorTerminals {
            get {
                return ResourceManager.GetString("ProcessorTerminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNC.
        /// </summary>
        public static string RNCNumber {
            get {
                return ResourceManager.GetString("RNCNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 1.
        /// </summary>
        public static string Telephone1 {
            get {
                return ResourceManager.GetString("Telephone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 2.
        /// </summary>
        public static string Telephone2 {
            get {
                return ResourceManager.GetString("Telephone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Entity.
        /// </summary>
        public static string TypeofEntity {
            get {
                return ResourceManager.GetString("TypeofEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCC Code.
        /// </summary>
        public static string TypeofIndustry {
            get {
                return ResourceManager.GetString("TypeofIndustry", resourceCulture);
            }
        }
    }
}
