//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pecuniaus.Resources.MerchantProfile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Collections {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Collections() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pecuniaus.Resources.MerchantProfile.Collections", typeof(Collections).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AEC Amount.
        /// </summary>
        public static string AECAmount {
            get {
                return ResourceManager.GetString("AECAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliation ID.
        /// </summary>
        public static string AffiliationID {
            get {
                return ResourceManager.GetString("AffiliationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount When Removed from Collection.
        /// </summary>
        public static string AmountWhenRemovedfromCollection {
            get {
                return ResourceManager.GetString("AmountWhenRemovedfromCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection ID.
        /// </summary>
        public static string CollectionID {
            get {
                return ResourceManager.GetString("CollectionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Type.
        /// </summary>
        public static string CollectionType {
            get {
                return ResourceManager.GetString("CollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract ID.
        /// </summary>
        public static string ContractID {
            get {
                return ResourceManager.GetString("ContractID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Entered.
        /// </summary>
        public static string DateEntered {
            get {
                return ResourceManager.GetString("DateEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Removed.
        /// </summary>
        public static string DateRemoved {
            get {
                return ResourceManager.GetString("DateRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Date.
        /// </summary>
        public static string FundingDate {
            get {
                return ResourceManager.GetString("FundingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Status.
        /// </summary>
        public static string MerchantStatus {
            get {
                return ResourceManager.GetString("MerchantStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owed Amount.
        /// </summary>
        public static string OwnedAmount {
            get {
                return ResourceManager.GetString("OwnedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention Time.
        /// </summary>
        public static string RetentionTime {
            get {
                return ResourceManager.GetString("RetentionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
    }
}
