//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pecuniaus.Resources.MerchantProfile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreditReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreditReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pecuniaus.Resources.MerchantProfile.CreditReport", typeof(CreditReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount in Legal.
        /// </summary>
        public static string AmountInLegal {
            get {
                return ResourceManager.GetString("AmountInLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Amount.
        /// </summary>
        public static string ApprovedAmount {
            get {
                return ResourceManager.GetString("ApprovedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Cards.
        /// </summary>
        public static string CreditCards {
            get {
                return ResourceManager.GetString("CreditCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt Index.
        /// </summary>
        public static string DebtIndex {
            get {
                return ResourceManager.GetString("DebtIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation.
        /// </summary>
        public static string Evaluation {
            get {
                return ResourceManager.GetString("Evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Amount.
        /// </summary>
        public static string LateAmount {
            get {
                return ResourceManager.GetString("LateAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Index.
        /// </summary>
        public static string LateIndex {
            get {
                return ResourceManager.GetString("LateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans.
        /// </summary>
        public static string Loans {
            get {
                return ResourceManager.GetString("Loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Payment.
        /// </summary>
        public static string MonthlyPayment {
            get {
                return ResourceManager.GetString("MonthlyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Loans.
        /// </summary>
        public static string NumberOfLoans {
            get {
                return ResourceManager.GetString("NumberOfLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owed Amount.
        /// </summary>
        public static string OwnedAmount {
            get {
                return ResourceManager.GetString("OwnedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Credit.
        /// </summary>
        public static string TotalCredit {
            get {
                return ResourceManager.GetString("TotalCredit", resourceCulture);
            }
        }
    }
}
