//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pecuniaus.Resources.MerchantProfile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Profiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Profiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pecuniaus.Resources.MerchantProfile.Profiles", typeof(Profiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Monthly CC Value.
        /// </summary>
        public static string AverageMonthlyCCValue {
            get {
                return ResourceManager.GetString("AverageMonthlyCCValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Monthly Ticket.
        /// </summary>
        public static string AverageMonthlyTicket {
            get {
                return ResourceManager.GetString("AverageMonthlyTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Yearly Sales.
        /// </summary>
        public static string GrossYearlySales {
            get {
                return ResourceManager.GetString("GrossYearlySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Credit Card Sales.
        /// </summary>
        public static string MonthlyCreditCardSales {
            get {
                return ResourceManager.GetString("MonthlyCreditCardSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        public static string Processor {
            get {
                return ResourceManager.GetString("Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        public static string ProcessorName {
            get {
                return ResourceManager.GetString("ProcessorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor No.
        /// </summary>
        public static string ProcessorNumber {
            get {
                return ResourceManager.GetString("ProcessorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Tickets.
        /// </summary>
        public static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
