//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pecuniaus.Resources.MerchantProfile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pecuniaus.Resources.MerchantProfile.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Value Is required.
        /// </summary>
        public static string AddressReq {
            get {
                return ResourceManager.GetString("AddressReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliation Number is required.
        /// </summary>
        public static string AffiliationReq {
            get {
                return ResourceManager.GetString("AffiliationReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Status is Required.
        /// </summary>
        public static string BusinessStatusReq {
            get {
                return ResourceManager.GetString("BusinessStatusReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Number is Required.
        /// </summary>
        public static string CellphoneReq {
            get {
                return ResourceManager.GetString("CellphoneReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Number must be Ten digit long.
        /// </summary>
        public static string CellphoneVal {
            get {
                return ResourceManager.GetString("CellphoneVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name is required.
        /// </summary>
        public static string CityReq {
            get {
                return ResourceManager.GetString("CityReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Became Owner is Required.
        /// </summary>
        public static string DateBecameOwnerReq {
            get {
                return ResourceManager.GetString("DateBecameOwnerReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Became Owner should be less than today&apos;s date.
        /// </summary>
        public static string DateBecameOwnerVal {
            get {
                return ResourceManager.GetString("DateBecameOwnerVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date the business started accepting CC is Required.
        /// </summary>
        public static string DateBusinessStartedCCReq {
            get {
                return ResourceManager.GetString("DateBusinessStartedCCReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date the business started accepting CC should be less than today&apos;s date.
        /// </summary>
        public static string DateBusinessStartedCCVal {
            get {
                return ResourceManager.GetString("DateBusinessStartedCCVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Business Started is Required.
        /// </summary>
        public static string DateBusinessStartedReq {
            get {
                return ResourceManager.GetString("DateBusinessStartedReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Business Started should be less than today&apos;s date.
        /// </summary>
        public static string DateBusinessStartedVal {
            get {
                return ResourceManager.GetString("DateBusinessStartedVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth is Required.
        /// </summary>
        public static string DOBReq {
            get {
                return ResourceManager.GetString("DOBReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date the Birth should be less than today&apos;s date.
        /// </summary>
        public static string DOBVal {
            get {
                return ResourceManager.GetString("DOBVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is Required.
        /// </summary>
        public static string EmailReq {
            get {
                return ResourceManager.GetString("EmailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Vaild Email Address.
        /// </summary>
        public static string EmailVal {
            get {
                return ResourceManager.GetString("EmailVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax number is required.
        /// </summary>
        public static string FaxReq {
            get {
                return ResourceManager.GetString("FaxReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Number must be Ten digit long.
        /// </summary>
        public static string FaxVal {
            get {
                return ResourceManager.GetString("FaxVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is Required.
        /// </summary>
        public static string FirstNameReq {
            get {
                return ResourceManager.GetString("FirstNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date is Required.
        /// </summary>
        public static string FromDateReq {
            get {
                return ResourceManager.GetString("FromDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date should be less than today&apos;s date.
        /// </summary>
        public static string FromDateVal {
            get {
                return ResourceManager.GetString("FromDateVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification is Required.
        /// </summary>
        public static string IdentificationReq {
            get {
                return ResourceManager.GetString("IdentificationReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord Company Name is Required.
        /// </summary>
        public static string LandlordCompanyNameReq {
            get {
                return ResourceManager.GetString("LandlordCompanyNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord Name is Required.
        /// </summary>
        public static string LandlordNameReq {
            get {
                return ResourceManager.GetString("LandlordNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is Required.
        /// </summary>
        public static string LastNameReq {
            get {
                return ResourceManager.GetString("LastNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Rent Amount should be greater than zero.
        /// </summary>
        public static string MonthlyRentAmountGreaterThanZero {
            get {
                return ResourceManager.GetString("MonthlyRentAmountGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Rent Amount is Required.
        /// </summary>
        public static string MonthlyRentAmountReq {
            get {
                return ResourceManager.GetString("MonthlyRentAmountReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Business is Required.
        /// </summary>
        public static string NameofBusinessReq {
            get {
                return ResourceManager.GetString("NameofBusinessReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Company is Required.
        /// </summary>
        public static string NameofCompanyReq {
            get {
                return ResourceManager.GetString("NameofCompanyReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is Required.
        /// </summary>
        public static string PositionReq {
            get {
                return ResourceManager.GetString("PositionReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province information is required.
        /// </summary>
        public static string ProvinceReq {
            get {
                return ResourceManager.GetString("ProvinceReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention Change Reason is Required.
        /// </summary>
        public static string RetentionChangeReasonReq {
            get {
                return ResourceManager.GetString("RetentionChangeReasonReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention Percentage is Required.
        /// </summary>
        public static string RetentionPercentageReq {
            get {
                return ResourceManager.GetString("RetentionPercentageReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNC Number is Required.
        /// </summary>
        public static string RNCReq {
            get {
                return ResourceManager.GetString("RNCReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNC Number must be Elevent digit long.
        /// </summary>
        public static string RNCVal {
            get {
                return ResourceManager.GetString("RNCVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number 1 is required.
        /// </summary>
        public static string Telephone1Req {
            get {
                return ResourceManager.GetString("Telephone1Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number 1 must be Ten digit long.
        /// </summary>
        public static string Telephone1Val {
            get {
                return ResourceManager.GetString("Telephone1Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number 2 is required.
        /// </summary>
        public static string Telephone2Req {
            get {
                return ResourceManager.GetString("Telephone2Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number 2 must be Ten digit long.
        /// </summary>
        public static string Telephone2Val {
            get {
                return ResourceManager.GetString("Telephone2Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date is Required.
        /// </summary>
        public static string ToDateReq {
            get {
                return ResourceManager.GetString("ToDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date should be less than From Date.
        /// </summary>
        public static string ToDateVal {
            get {
                return ResourceManager.GetString("ToDateVal", resourceCulture);
            }
        }
    }
}
